INCLUDEDIR = ../include
OBJECTSDIR = ./obj
CFLAGS =-I$(INCLUDEDIR) -g -Wall


all:
	gcc -o ../test test.c -L.. -lmytui  $(CFLAGS)
	gcc -o ../test2 test2.c -L.. -lmytui  $(CFLAGS)
	gcc -o ../test3 test3.c -L.. -lmytui  $(CFLAGS)
	gcc -o ../test4 test4.c -L.. -lmytui  $(CFLAGS)
