INCLUDEDIR = ../../src/include
OBJECTSDIR = ./obj
CFLAGS =-I$(INCLUDEDIR) -g -Wall


all:
	gcc -o ../../bin/vtest vtest.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../bin/vtest2 vtest2.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../bin/vtest3 vtest3.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../bin/vtest4 vtest4.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../bin/vtest5 vtest5.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../bin/vtest6 vtest6.c -L../.. -lmytui  $(CFLAGS)
