INCLUDEDIR = ../../src/include
OBJECTSDIR = ./obj
CFLAGS =-I$(INCLUDEDIR) -g -Wall


all:
	gcc -o ../../vtest vtest.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../vtest2 vtest2.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../vtest3 vtest3.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../vtest4 vtest4.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../vtest5 vtest5.c -L../.. -lmytui  $(CFLAGS)
