INCLUDEDIR = ../../src/include
OBJECTSDIR = ./obj
CFLAGS =-I$(INCLUDEDIR) -g -Wall


all:
	gcc -o ../../bin/vtest1 vtest1.c -L../.. -lmytui  $(CFLAGS)
	gcc -o ../../bin/vtest2 vtest2.c -L../.. -lmytui  $(CFLAGS)
